config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  namespace :dashboard do
    get 'main/index'
    root 'main#index'
    resources :orders

    post 'add_item_count/:id/:order_id' => 'product_items#add_item_count', as: :add_item_count
    post 'sub_item_count/:id/:order_id' => 'product_items#sub_item_count', as: :sub_item_count
    post 'order/:id/finish_check' => 'orders#finish_check', as: :finish_check
  end

  mount Sidekiq::Web => '/sidekiq'
  
  get 'main/index'
  root 'main#index'

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register', sign_up: 'join_us'  }

end

app/models/order.rb
class Order < ActiveRecord::Base
  extend Enumerize

  belongs_to :originzer, class_name: 'User', foreign_key: "user_id"
  has_many :user_item_ables
  has_one  :shop

  enumerize :is_success, in: [ 0, 1 ]

  scope :succeed, -> { where(is_success: 1) }

  private

    def self.find_by_id(id)
      where(id: id).first
    end
end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base
  belongs_to :shop
  has_many :user_item_ables
  has_many :users, through: :user_item_ables
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :product_items
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  attr_accessor :login

  has_many :origin_orders, class_name: "Order"
  has_many :user_item_ables
  has_many :product_items, through: :user_item_ables


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    find_first_by_auth_conditions(warden_conditions)
  end


  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
  
end

app/models/user_item_able.rb
class UserItemAble < ActiveRecord::Base
  belongs_to :user
  belongs_to :product_item
  belongs_to :order
  # after_update :check_count

  # def check_count
  #   self.destory! if count <= 0
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :username, :phone_number, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  def layout_by_resource
    if devise_controller? && resource_name == :user
      "auth"
    else
      "application"
    end
  end
  
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

end

app/controllers/dashboard/main_controller.rb
class Dashboard::MainController < Dashboard::BaseController
  
  def index
    @orders = Order.succeed
  end

end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < Dashboard::BaseController
  def index
    @order = Order.new
    @orders = current_user.origin_orders
  end

  def create
    @order = Order.new(user_params)
    @order.originzer = current_user
    @order.save
    CrawlTdd.perform_async(@order.id)
    redirect_to dashboard_orders_url
  end

  def show
    @order = Order.find(params[:id])
    @hash = {}
    @order.user_item_ables.where(order_id: @order.id).each do |item|
      name = item.product_item.name
      if @hash[name]
        @hash[name] += item.count
      else
        @hash[name] = item.count
      end
    end
  end

  def finish_check
    @order = Order.find(params[:id])
    @order.update(is_success: 2)
    redirect_to dashboard_order_path(@order)
  end

  private

  def user_params
    params.require(:order).permit(:source_url, :finish_time, :content)
  end


end

app/controllers/dashboard/product_items_controller.rb
class Dashboard::ProductItemsController < Dashboard::BaseController
  def add_item_count
    common_change_item_count(1)
    render :change_item_count
  end

  def sub_item_count
    common_change_item_count(-1)
    @user_item_able.destroy if @user_item_able && @user_item_able.count <= 0
    render :change_item_count
  end

  private

  def common_change_item_count(number)
    @product_item = ProductItem.find(params[:id])
    @user_item_ables = UserItemAble.where(user_id: current_user.id, product_item_id: @product_item.id)
    if @user_item_ables.length > 0
      @user_item_able = @user_item_ables.first
      @user_item_able.update(count: @user_item_able.count + number) if @user_item_able.count + number >= 0
    else
      @user_item_able = UserItemAble.create(user: current_user, product_item: @product_item, order_id: params[:order_id], count: 1) if number > -1
    end

    @user_item_ables = current_user.user_item_ables.where(order_id: params[:order_id])

  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/dashboard/base_helper.rb
module Dashboard::BaseHelper
end

app/helpers/dashboard/main_helper.rb
module Dashboard::MainHelper
end

app/helpers/dashboard/order_helper.rb
module Dashboard::OrderHelper

  def shop_name(order)
    if order.shop
      return order.shop.name
    else
      return "正在获取"
    end
  end

  def success_status(number)
    if number == 0
      ""
    elsif number == 1
      "正在点餐"
    elsif number == 2
      "点餐结束"
    else
      number
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/dashboard/main/index.html.slim
.row.fix_row
  .col-md-12.col-sm-12.col-sx-12
    .panel.panel-default
      .panel-heading.clearfix
        i.icon-list
        h3.panel-title 点餐列表
      .panel-body
        .table-responsive
          table.table.table.-bordered.no-margin
            thead
              tr
                th style="width:20%" 
                  | ID
                th style="width:15%" 
                  | 发起人
                th style="width:15%" 
                  | 结束时间
                th style="width:20%" 
                  | 报名人数
                th style="width:20%" 
                  | 餐厅
                th style="width:10%" 
                  | \&nbsp;
            tbody

              - @orders.each do |order|
                tr
                  td = order.id
                  td = order.originzer.username
                  td = order.finish_time.strftime('%Y-%m-%d %H:%M:%S')
                  td 12
                  td = shop_name(order)
                  td
                    = link_to '加入', dashboard_order_path(order), class: 'label label-success'
              

app/views/dashboard/orders/index.html.slim
.row.fix_row
  .col-md-6.col-sm-6.col-sx-6
    .panel.panel-default
      .panel-heading.clearfix
        i.icon-list
        h3.panel-title 点餐
      .panel-body
        .table-responsive
          = simple_form_for @order, url: dashboard_orders_url() do |f|
            = f.input :source_url, as: :url, label: '淘点点店铺地址', input_html: {class: 'form-control'}, label_html: { class: 'control_label' }, wrapper_html: { class: 'wrapper' }
            = f.input :finish_time, label: '时间', input_html: {class: ''}, label_html: { class: 'control_label' }, wrapper_html: { class: 'wrapper' }
            = f.input :content, as: :string, label: '内容', input_html: {class: 'form-control'}, label_html: { class: 'control_label' }, wrapper_html: { class: 'wrapper' }
            = f.button :submit, "提交", class: 'wrapper btn btn-info'


  .col-md-6.col-sm-6.col-sx-6
    .panel.panel-default
      .panel-heading.clearfix
        i.icon-list
        h3.panel-title 我没完成的订单
      .panel-body
        .table-responsive
          table.table.table.-bordered.no-margin
            thead
              tr
                th style="width:10%" ID
                th style="width:20%" 结束时间
                th style="width:15%" 报名人数
                th style="width:34%" 餐厅
                th style="width:10%" 状态
                th style="width:10%"  \&nbsp;
            tbody
              - @orders.each do |order|
                tr
                  td =order.id
                  td =order.finish_time.strftime('%Y-%m-%d %H:%M')
                  td 12
                  td = shop_name(order)
                  td = success_status(order.is_success)
                  - if order.is_success > 0
                    td  = link_to '查看', dashboard_order_path(order), class: 'label label-success'              

app/views/dashboard/orders/show.html.slim
.row.fix_row
  .col-md-12.col-sm-12.col-sx-12
    .panel.panel-default
      .panel-heading.clearfix
        i.icon-calendar
        h3.panel-title 要点的菜
      .panel-body
        p.big.label.label-info = "店名: #{@order.shop.name}"
        p.small = "地址: #{@order.shop.address}"
        p.small = "电话: #{@order.shop.tel}"
        p.small = "网址: #{@order.shop.source_url}"
        ul#total_detail
         - @hash.each do |item|
          li = "#{item.first}----#{item.last}"
        - if @order.is_success == 1
          = link_to '点餐结束', dashboard_finish_check_path(@order), class: 'btn btn-danger', method: 'POST'

.row.fix_row
  .col-md-8.col-sm-8.col-sx-8
    .panel.panel-default
      .panel-heading.clearfix
        i.icon-calendar
        h3.panel-title 菜品
      .panel-body
        .row
          -@order.shop.product_items.each do |item|
            .col-sm-6.col-md-3
              .thumbnail
                = image_tag(item.image_url, class: 'img-responsive', alt: item.name) 
                .caption.caption_fix
                  p.item_name = item.name
                  - if @order.is_success == 1
                    p
                      = link_to "加一个", dashboard_add_item_count_path(item, @order.id), class: "btn btn-primary", method: 'POST', remote: true 
                      = link_to "减一个", dashboard_sub_item_count_path(item, @order.id), class: "btn btn-default", method: 'POST',remote: true 


  .col-md-4.col-sm-4.col-sx-4
    .pin-cart
      .pinned.note-container 
        .note
          h3 我点的餐
          div
            ul#cart_detail
              - @hash.each do |item|
                li = "#{item.first} * #{item.last}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheniuCallLunch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/auth.html.slim
doctype html
html
  head
    title 车牛点餐 - Login
    meta charset="utf-8" 
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body#login-body
    #login-container
      #logo
        | 
        sup
          i.icon-glass
      #login
        h3
          | 车牛
          span 点餐
        h5 人是铁，饭是钢
        
        = yield

app/views/layouts/dashboard.html.slim
doctype html
html
  head
    title 车牛点餐 - 首页
    meta charset="utf-8" 
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    
    = csrf_meta_tags
  body
    .container
      .top-bar
        .logo
          | 车牛点餐
          sup
            i.icon-glass
        /! Icon nav start
        ul#icon-nav
          li
            a data-original-title="" href="#" title="" 
              i.icon-bell
              span.count-label
          li
            a data-original-title="" href="#" title="" 
              i.icon-comment-alt
              span.count-label.count-lb-yellow
          li
            a data-original-title="" href="#" title="" 
              i.icon-envelope-alt
              span.count-label.count-lb-green
        /! Icon nav end
      header.navbar role="navigation" 
        .navbar-header
          button.navbar-toggle data-original-title="" data-target=".bs-navbar-collapse" data-toggle="collapse" title="" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand data-original-title="" href="#" title=""  &nbsp;
        nav.collapse.navbar-collapse.bs-navbar-collapse role="navigation" 
          ul.nav.navbar-nav
            li
              = link_to "列表", dashboard_root_url()
            li
              = link_to "管理", dashboard_orders_url()

          /! Mini navigation start
          ul.nav.navbar-nav.navbar-right.hidden-sm.hidden-xs
            li.dropdown
              a.dropdown-toggle data-original-title="" data-toggle="dropdown" href="#" title="" 
                i.icon-user
                = current_user.username
                b.caret
              ul.dropdown-menu
                li
                  = link_to "退出", destroy_user_session_path(), method: :delete

      = yield

      = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/main/index.html.slim
h1 Main#index
p Find me in app/views/main/index.html.slim

div
  p = current_user.username
  p = current_user.phone_number
  p = current_user.email
  p = link_to "退出", destroy_user_session_path(), method: :delete

div
  p = link_to "用户中心", dashboard_root_path()

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>